{
  "hash": "fed804eb299b17a910b780de13c52918",
  "result": {
    "markdown": "---\nexecute:\n  message: false\n  warning: false\n  fig-show: no\ntitle: \"Vinos 2021, análisis descriptivo\"\nauthor: \"FV\"\ndate: \"2024-06-03\"\ncategories: [code, analysis]\nimage: \"vinos.jpg\"\n---\n\n\nEl objetivo es extraer información útil a partir de un análisis estadístico para este marco de datos.\n\nEl archivo VINOS.csv recopila datos sobre el precio de venta y otras\ncaracterísticas de una muestra aleatoria de 6496 tipos diferentes de vinos\nde la D.O de Utiel-Requena, Comunidad Valenciana, España.\n\n## 1.- Calidad del vino\n\nSe cargan las librerías: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(nortest)\nlibrary(showtext)\n```\n:::\n\n\nSe cargan las fuentes de texto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfont_add_google(\"Luckiest Guy\",\"ramp\")\nfont_add_google(\"Bebas Neue\",\"beb\")\nfont_add_google(\"Fira Sans\",\"fira\")\nfont_add_google(\"Raleway\",\"ral\")\nfont_add_google(\"Bitter\",\"bit\")\nshowtext_auto()\n```\n:::\n\n\nSe carga la base de datos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvinos <- read.csv2(\"VINOS.csv\")\n```\n:::\n\n\nSe verifica previamente la información básica de los datos (tipo de variables y la dimensión):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(vinos)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t5112 obs. of  8 variables:\n $ X        : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Tipo     : chr  \"Tinto\" \"Tinto\" \"Tinto\" \"Tinto\" ...\n $ pH       : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...\n $ Sulfatos : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...\n $ Alcohol  : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...\n $ Tonalidad: chr  \"Azulado\" \"Azulado\" \"Azulado\" \"Azulado\" ...\n $ Calidad  : int  5 5 5 6 5 5 5 7 7 5 ...\n $ Precio   : num  3.5 2.01 3.27 3.46 2.14 3.36 3.18 5.82 5.32 3.89 ...\n```\n:::\n:::\n\n\n- PH, Sulfatos, Alcohol, Tobalidad y Precio, son variables numericas.\n- X y Calidad son variables de tipo entero.\n- Tipo, variable de tipo char. \n\nSe ejecuta la instrucción \"summary\" para conocer algunos valores estadísticos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(vinos$Calidad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   3.00    5.00    6.00    5.75    6.00    9.00 \n```\n:::\n:::\n\n\nSe traza un gráfico de barras:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(vinos, aes(x=Calidad, fill=Tonalidad)) +\n  geom_histogram(bins = 8,  colour='white', size=.1) +\n  ggtitle(\"Gráfico de barras: Vinos-Calidad\") +\n    scale_fill_manual(values=c(\"#304bae\", \"#f5f7c0\",\"#ab2a3e\", \"#c9af4f\",\"#c85c5c\", \"#61b15b\"))+\n  theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nEntre los valores 5 y 6 se encuentra la mayor concentración de la calidad de los vinos, con una mediana de 6 y con frecuencias superior a 1500. \n\nTabla de frecuencias (Calidad de vinos):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalidad <- vinos$Calidad\ncalidad <- table(calidad)\ncalidad\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncalidad\n   3    4    5    6    7    8    9 \n  22  176 1849 2204  737  119    5 \n```\n:::\n:::\n\n\nSe seleccionan las variables Tipo y Calidad en un marco de datos de nombre calidad_t con la finalidad de hacer una tabla de frecuencias usando la función table().\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalidad_t <- select(vinos, Tipo, Calidad)\ncalidad_t <- table(calidad_t)\ncalidad_t <- as.data.frame(calidad_t)\ncalidad_t\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Tipo Calidad Freq\n1  Blanco       3   12\n2   Tinto       3   10\n3  Blanco       4  125\n4   Tinto       4   51\n5  Blanco       5 1180\n6   Tinto       5  669\n7  Blanco       6 1639\n8   Tinto       6  565\n9  Blanco       7  604\n10  Tinto       7  133\n11 Blanco       8  110\n12  Tinto       8    9\n13 Blanco       9    5\n14  Tinto       9    0\n```\n:::\n:::\n\n\n\nSe seleccionan las variables Tonalidad y Calidad en un marco de datos de nombre calidad_tt con la finalidad de obtener otra tabla de frecuencias.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalidad_tt <- select(vinos, Tonalidad, Calidad)\ncalidad_tt <- table(calidad_tt)\ncalidad_tt <- as.data.frame(calidad_tt)\nhead(calidad_tt, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Tonalidad Calidad Freq\n1    Azulado       3    6\n2     Dorado       3    4\n3    Granate       3    3\n4       Ocre       3    2\n5       Rojo       3    1\n6    Verdoso       3    6\n7    Azulado       4   24\n8     Dorado       4   55\n9    Granate       4   13\n10      Ocre       4    9\n```\n:::\n:::\n\n\nSe pueden notar frecuencias altas para el vino Tipo blanco, y además, frecuencias altas para los vinos de Tonalidad Verdoso y Azulado. Los valores de Calidad en general se concentran principalmente en los valores 5 y 6. \n\n## 2.- Relación entre la calidad del vino y la tonalidad que presenta\n\nSe seleccionan las variables Tipo y Tonalidad en un marco de datos de nombre calidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalidad <- select(vinos, Calidad, Tipo, Tonalidad)\n```\n:::\n\n\nSe verifica el tipo de variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(calidad)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t5112 obs. of  3 variables:\n $ Calidad  : int  5 5 5 6 5 5 5 7 7 5 ...\n $ Tipo     : chr  \"Tinto\" \"Tinto\" \"Tinto\" \"Tinto\" ...\n $ Tonalidad: chr  \"Azulado\" \"Azulado\" \"Azulado\" \"Azulado\" ...\n```\n:::\n:::\n\n\nTipo Y Tonaliadad son variables de tipo Char, Calidad es una variable númerica.\n\nSe hace un gráfico ggplot usando un fill para diferenciar las categorias blanco y tinto:\n\n### Tipo: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vinos, aes(x=Calidad, fill=Tipo, color=Tipo)) +\n  ggtitle(\"Tipos de vino\") +\n  geom_histogram(alpha=2, position=\"identity\", bins = 8, size=.1)+\n  geom_density(alpha=0.5) +\n  xlab(\"Calidad\") +\n  ylab(\"Frecuencias\") +\n  scale_color_manual(values=c(\"white\", \"white\"))+\n  scale_fill_manual(values=c(\"#e9e4e4\", \"#c85c5c\")) +\n    theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nSe puede notar que ambos vinos concentran su calidad entre 5 y 6, con mayor número de frecuencuas para el vino blanco. Es claro que el vino predominante es el vino Tipo Blanco. \n\n### Tonalidad: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vinos, aes(x=Calidad, fill=Tonalidad, color=Tonalidad)) +\n  ggtitle(\"Tipos de vino - Tonalidad\") +\n  geom_histogram(alpha=1, position=\"identity\", bins = 8, size=.1, color=\"white\")+\n  geom_density(alpha=1) +\n  xlab(\"Calidad\") +\n  ylab(\"Frecuencias\") +\n  scale_color_manual(values=c(\"#304bae\", \"#f5f7c0\",\"#ab2a3e\", \"#c9af4f\",\"#c85c5c\", \"#61b15b\"))+\n  scale_fill_manual(values=c(\"#304bae\", \"#f5f7c0\",\"#ab2a3e\", \"#c9af4f\",\"#c85c5c\", \"#61b15b\")) +\n    theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nSegún el Tipo de Tonalidad, el vino predominante es el verdoso y en segundo lugar el vino Ocre. Los vinos con Tonalidad Azulado, Dorado, Granate y Rojo, presentan frecuencias muy bajas en su Tonalidad. \n\n\n## 3.- Graduación alcohólica del vino\n\nPara realizar un análisis descriptivo de la variable Alcohol, variable que recoge la graduación alcohólica que presentan los distintos tipos de vinos analizados. Se verifican algunos valores estadísticos usando la función summary()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(vinos$Alcohol)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   8.40    9.50   10.10   10.38   10.80   14.20 \n```\n:::\n:::\n\n\nGráfico de bigotes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vinos, aes(x=0, y=Alcohol)) +\n  geom_boxplot(bg=\"#304bae\") +\n  ggtitle(\"Boxplot: Vinos-Alcohol\") +\n    theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nCon el gráfico de bigotes se puede notar la presencia de algunos datos atípicos, es decir con muy pocas ocurrencias y que marcan vinos con más de 13 en nivel de alcohol. La mediana se ubica en 10.10. Los niveles de alcohol se concentran entre 9.50 y 10.80.\n\n\n###Gráfico de barras:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vinos, aes(x=Alcohol, fill=Tipo, color=Tipo)) +\n  ggtitle(\"Tipos de vino: Alcohol-Tipo\") +\n  geom_histogram(alpha=2, position=\"identity\", bins = 30)+\n  geom_density(alpha=0.5) +\n  xlab(\"Calidad\") +\n  ylab(\"Frecuencias\") +\n  scale_color_manual(values=c(\"#61b15b\", \"#304bae\"))+\n  scale_fill_manual(values=c(\"#e9e4e4\", \"#c85c5c\")) +\n    theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(vinos, aes(x=Alcohol, fill=Tonalidad, color=Tonalidad)) +\n  ggtitle(\"Tipos de vino: Alcohol-Tonalidad\") +\n  geom_histogram(alpha=1, position=\"identity\", bins = 10)+\n  geom_density(alpha=1) +\n  xlab(\"Nivel de alcohol\") +\n  ylab(\"Frecuencias\") +\n  scale_fill_manual(values=c(\"#304bae\", \"#f5f7c0\",\"#ab2a3e\", \"#c9af4f\",\"#c85c5c\", \"#61b15b\"))+\n  scale_color_manual(values=c(\"#abaaaa\", \"#abaaaa\",\"#abaaaa\", \"#abaaaa\",\"#abaaaa\", \"#abaaaa\")) +\n      theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nPrueba de normalidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(vinos$Alcohol, pch = 19, col = \"gray50\")\nqqline(vinos$Alcohol)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nLos datos de la variable Alcohol parecen estar distribuidos de manera normal, sin embargo no puede afirmarse totalmente. En los extremos parecen alejare mucho de la línea qqline. \n\n## 4.- Precio y graduación alcohólica del vino\n\nSe seleccionan las variables Alcohol y Precio para verificar sus relaciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio_a <- select(vinos, Alcohol, Precio)\nsummary(precio_a)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Alcohol          Precio     \n Min.   : 8.40   Min.   :2.000  \n 1st Qu.: 9.50   1st Qu.:3.180  \n Median :10.10   Median :4.170  \n Mean   :10.38   Mean   :4.148  \n 3rd Qu.:10.80   3rd Qu.:5.110  \n Max.   :14.20   Max.   :6.980  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(viridis)\nggplot(precio_a, aes(y=Alcohol, x=Precio)) +\n  geom_point( aes(color=Precio),  alpha = 0.7) +\n  ggtitle(\"Tipos de vino: Precio-Alcohol\") +\n  xlab(\"Precio (€)\") +\n  ylab(\"Alcohol\") +\n  scale_color_viridis(discrete = F, direction=-1, option = \"C\") +\n      theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(vinos$Alcohol ~ vinos$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nEn el gráfico se puede notar que los vinos de menor grado de alcohol pueden costar precios altos y bajos, y los de mayor grado de alcohol tambíen tienen precios altos y bajos. No parece existir una tendencia evidente o sólida para afirmar que el precio influye respecto a sus niveles de alcohol. \n\n## 5. Relación entre el precio del vino y el valor de la variable calidad\n\nSe seleccionan las variables Calidad y Precio para verificar sus relaciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio <- select(vinos, Calidad, Precio)\nsummary(precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Calidad         Precio     \n Min.   :3.00   Min.   :2.000  \n 1st Qu.:5.00   1st Qu.:3.180  \n Median :6.00   Median :4.170  \n Mean   :5.75   Mean   :4.148  \n 3rd Qu.:6.00   3rd Qu.:5.110  \n Max.   :9.00   Max.   :6.980  \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio$Calidad <- as.character(precio$Calidad)\nggplot(precio, aes(x=Precio, fill=Calidad)) +\n  geom_histogram(bins = 30, colour='white', size=.1) +\n    ggtitle(\"Tipos de vino: Precio-Calidad\") +\n  xlab(\"Precio (€)\") +\n  ylab(\"Cantidad\") +\n  scale_fill_viridis(discrete = T, direction=-1, option = \"C\") +\n      theme(\n    text = element_text(family = \"fira\"),\n    panel.grid = element_blank(),\n    plot.title = element_text(size = 16, colour = \"gray20\", face=\"bold\"),\n    axis.text.y = element_text(size = 10, colour = \"gray20\"),\n    axis.title.x = element_text(size = 10, colour = \"gray20\"),\n    axis.title.y = element_text(size = 10, colour = \"gray20\"),\n    panel.background = element_rect(fill = 'white', color = 'white')\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\nClaramente se nota que entre mayor calidad de vino, mayor el precio. En promedio un vino de calidad 6 cuesta un poco más de 4.  \n\n\n## 7.- Precio medio de los vinos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(vinos$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  2.000   3.180   4.170   4.148   5.110   6.980 \n```\n:::\n\n```{.r .cell-code}\nmean(vinos$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.147788\n```\n:::\n:::\n\n\nEl precio medio de los vinos es de 4.147788 y con una mediana de 4.148. \n\nSe hace la prueba t.test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x=vinos$Precio, y = NULL,\n       alternative = c(\"two.sided\", \"less\", \"greater\"),\n       mu = 4.25, paired = FALSE, var.equal = FALSE,\n       conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  vinos$Precio\nt = -6.116, df = 5111, p-value = 1.031e-09\nalternative hypothesis: true mean is not equal to 4.25\n95 percent confidence interval:\n 4.115024 4.180551\nsample estimates:\nmean of x \n 4.147788 \n```\n:::\n:::\n\n\nCon 95% de confianza se puede asegurar que los valores del precio del vino se ubican entre  4.115024 y 4.180551 Euros. Lo que significa que es inferior a los 4.25 planteados en el interrogante. \n\n\n##  8.- Precio medio de los vinos con Tonalidad Verdoso\n\nSe seleccionan las variables Calidad y Precio para verificar sus relaciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio_ver <- filter(vinos, Tonalidad==\"Verdoso\")\nsummary(precio_ver$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  2.000   2.680   3.280   3.473   4.260   5.970 \n```\n:::\n:::\n\nEl precio medio de los vinos de Tonaldad verdoso es de 3.473 Euros. Se platea una prueba t con un 90% de confianza:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x=precio_ver$Precio, y = NULL,\n       alternative = c(\"two.sided\", \"less\", \"greater\"),\n       mu = 3.473, paired = FALSE, var.equal = FALSE,\n       conf.level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  precio_ver$Precio\nt = 0.016029, df = 1605, p-value = 0.9872\nalternative hypothesis: true mean is not equal to 3.473\n90 percent confidence interval:\n 3.432355 3.514445\nsample estimates:\nmean of x \n   3.4734 \n```\n:::\n:::\n\n\nCon un 90% de confianza se puede asegurar que el precio del vino de Tonalidad verdoso se ubica entre 3.432355 y 3.514445 Euros. Un poco menos de lo planteado en el interronte. \n\n\n## 9.- Graduación alcohólica de los vinos cuya calidad presenta un valor de 8\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(precio_ver$Alcohol)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  9.000   9.200   9.400   9.413   9.600   9.900 \n```\n:::\n\n```{.r .cell-code}\nqqnorm(precio_ver$Alcohol)\nqqline(precio_ver$Alcohol)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nortest) \nad.test(precio_ver$Alcohol)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAnderson-Darling normality test\n\ndata:  precio_ver$Alcohol\nA = 21.521, p-value < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(precio_ver$Alcohol, alternative='two.sided',\n       conf.level=0.99, mu=11.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  precio_ver$Alcohol\nt = -367.69, df = 1605, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 11.9\n99 percent confidence interval:\n 9.395225 9.430117\nsample estimates:\nmean of x \n 9.412671 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(precio_ver$Alcohol, alternative='two.sided',\n       conf.level=0.95, mu=11.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  precio_ver$Alcohol\nt = -367.69, df = 1605, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 11.9\n95 percent confidence interval:\n 9.399402 9.425940\nsample estimates:\nmean of x \n 9.412671 \n```\n:::\n:::\n\nEl p-value es mucho menor que el nivel de significancia de 5% y 1%. Con un nivel de confianza del 99% \n\n\n\n## 10.- Comparación de la graduación alcohólica de los vinos cuya calidad presenta un valor de 8 y un valor de 4.\n\nEn primer lugar se verifica la homogeneidad de varianzas:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x=vinos$Alcohol, y = NULL,\n       alternative = c(\"two.sided\", \"less\", \"greater\"),\n       mu = 8, paired = FALSE, var.equal = FALSE,\n       conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  vinos$Alcohol\nt = 148.41, df = 5111, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 8\n95 percent confidence interval:\n 10.34518 10.40797\nsample estimates:\nmean of x \n 10.37657 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x=vinos$Alcohol, y = NULL,\n       alternative = c(\"two.sided\", \"less\", \"greater\"),\n       mu = 4, paired = FALSE, var.equal = FALSE,\n       conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  vinos$Alcohol\nt = 398.19, df = 5111, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 4\n95 percent confidence interval:\n 10.34518 10.40797\nsample estimates:\nmean of x \n 10.37657 \n```\n:::\n:::\n\n\nCon un intervalo de confianza de 95% se puede afirmar que el rango de graduación alcohólica no varia demasiado, sea con mu de 4 o de 8. \n\n## 11.- Comprobación de las condiciones de normalidad de la variable precio para la tonalidad Granate\n\nSe seleccionan las variables Precio y Tonalidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio_granate <- select(vinos, Precio, Tonalidad)\nprecio_granate <- filter(precio_granate, Tonalidad==\"Granate\")\nhead(precio_granate, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Precio Tonalidad\n1    5.82   Granate\n2    3.89   Granate\n3    3.39   Granate\n4    5.62   Granate\n5    5.39   Granate\n6    4.98   Granate\n7    5.54   Granate\n8    3.93   Granate\n9    3.23   Granate\n10   4.02   Granate\n11   5.07   Granate\n12   4.15   Granate\n13   5.35   Granate\n14   5.11   Granate\n15   4.71   Granate\n16   4.88   Granate\n17   4.50   Granate\n18   4.30   Granate\n19   4.24   Granate\n20   3.18   Granate\n```\n:::\n:::\n\n\nPrueba gráfica de normalidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(precio_granate$Precio)\nqqline(precio_granate$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(precio_granate$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-35-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlillie.test(precio_granate$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  precio_granate$Precio\nD = 0.039675, p-value = 0.08544\n```\n:::\n:::\n\n\n\nComo el p_value es mayor al 5%, por ende no se rechaza la hipotesis nula para el precio del vino de Tonalidad Granate, lo cual significa que los datos tienen un comportamiento normal. \n\n\n## 12.- Comprobación del cumplimiento de las condiciones de normalidad de la variable precio para la tonalidad Azulado y para la tonalidad Dorado\n\nSe seleccionan las variables Precio y Tonalidad:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio_azulado <- select(vinos, Precio, Tonalidad)\nprecio_azulado <- filter(precio_azulado, Tonalidad==\"Azulado\")\nhead(precio_azulado, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Precio Tonalidad\n1    3.50   Azulado\n2    2.01   Azulado\n3    3.27   Azulado\n4    3.46   Azulado\n5    2.14   Azulado\n6    3.36   Azulado\n7    3.18   Azulado\n8    5.32   Azulado\n9    2.23   Azulado\n10   2.07   Azulado\n11   3.20   Azulado\n12   2.13   Azulado\n13   2.31   Azulado\n14   2.51   Azulado\n15   2.29   Azulado\n16   4.31   Azulado\n17   5.06   Azulado\n18   3.48   Azulado\n19   2.07   Azulado\n20   2.21   Azulado\n```\n:::\n:::\n\n\nSe hace la prueba de normalidad (AZULADO):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(precio_azulado$Precio)\nqqline(precio_azulado$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(precio_azulado$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  precio_azulado$Precio\nt = 95.1, df = 679, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 3.147974 3.280702\nsample estimates:\nmean of x \n 3.214338 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlillie.test(precio_azulado$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  precio_azulado$Precio\nD = 0.12293, p-value < 2.2e-16\n```\n:::\n:::\n\n\nComo el p_value es menor al 5%, por ende se rechaza la hipotesis nula para el precio del vino de Tonalidad Azulado, lo cual significa que no se asemeja a una distribución normal. \n\n\nSe hace la prueba de normalidad (DORADO):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprecio_dorado <- select(vinos, Precio, Tonalidad)\nprecio_dorado <- filter(precio_dorado, Tonalidad==\"Dorado\")\nhead(precio_dorado, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Precio Tonalidad\n1    3.28    Dorado\n2    4.57    Dorado\n3    4.14    Dorado\n4    5.66    Dorado\n5    4.32    Dorado\n6    4.97    Dorado\n7    4.21    Dorado\n8    4.26    Dorado\n9    5.18    Dorado\n10   5.17    Dorado\n11   5.28    Dorado\n12   3.92    Dorado\n13   3.87    Dorado\n14   5.01    Dorado\n15   4.32    Dorado\n16   4.95    Dorado\n17   5.16    Dorado\n18   3.60    Dorado\n19   5.17    Dorado\n20   4.28    Dorado\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(precio_dorado$Precio)\nqqline(precio_dorado$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(precio_dorado$Precio)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-42-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(precio_dorado$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  precio_dorado$Precio\nt = 179.27, df = 1255, p-value < 2.2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 4.300230 4.395391\nsample estimates:\nmean of x \n 4.347811 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlillie.test(precio_azulado$Precio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  precio_azulado$Precio\nD = 0.12293, p-value < 2.2e-16\n```\n:::\n:::\n\n\nComo el p_value es menor al 5%, por ende se rechaza la hipotesis nula para el precio del vino de Tonalidad Dorado, lo cual significa que no se asemeja a una distribución normal, aunque tiene una similitud que puede resultar engañosa. \n\n![](vinos.jpg)\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}